name        = "lace_shared"
description = "Default settings for GPR files in the Lace project."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"
