-- This file is generated by SWIG. Please do *not* modify by hand.
--
with bullet_c.Pointers;


package bullet_c.pointer_Pointers
is

   --- Shape_pointer_pointer
   --

   type Shape_pointer_pointer is access all bullet_c.Pointers.Shape_pointer;


   --- Object_pointer_pointer
   --

   type Object_pointer_pointer is access all bullet_c.Pointers.Object_pointer;


   --- Joint_pointer_pointer
   --

   type Joint_pointer_pointer is access all bullet_c.Pointers.Joint_pointer;


   --- Space_pointer_pointer
   --

   type Space_pointer_pointer is access all bullet_c.Pointers.Space_pointer;


end bullet_c.pointer_Pointers;
