name        = "lace_xml"
description = "Provides simple XML read/write support."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"

project-files = ["library/xml.gpr"]

[[depends-on]]
lace_shared = "~0.1"
libexpat    = "*"
