with
     interfaces.C,
     System;


package Swig
--
-- Contains Swig related C type definitions not found in the 'interfaces.C' family,
-- as used by bindings generated by the 'swig4ada' tool.
--
is
   pragma Pure;


   -- Elementary types.
   --

   subtype void                  is System.Address;     -- The target of a 'void*'.
   subtype void_ptr              is System.Address;     -- A 'void*'.

   subtype opaque_structure      is System.Address;     -- A pointer to a struct whose layout is not modelled.
   subtype incomplete_class      is System.Address;     -- A pointer to a class  whose layout is not modelled.


   subtype long_Long             is interfaces.C.long_long;
   subtype unsigned_long_Long    is interfaces.C.unsigned_long_long;

   type    intptr_t              is range -(2 ** (Standard'address_Size - Integer'(1))) .. +(2 ** (Standard'address_Size - Integer'(1)) - 1);
   type   uintptr_t              is mod 2**Standard'address_Size;


   subtype int8_t                is interfaces.Integer_8;
   subtype int16_t               is interfaces.Integer_16;
   subtype int32_t               is interfaces.Integer_32;
   subtype int64_t               is interfaces.Integer_64;

   subtype uint8_t               is interfaces.Unsigned_8;
   subtype uint16_t              is interfaces.Unsigned_16;
   subtype uint32_t              is interfaces.Unsigned_32;
   subtype uint64_t              is interfaces.Unsigned_64;

   subtype bool                  is interfaces.C.C_bool;     -- A C 'bool'; convert to and from Boolean directly.



   -- Elementary Arrays
   --

   type void_ptr_array           is array (interfaces.C.size_t range <>) of aliased swig.void_ptr;
   type size_t_array             is array (interfaces.C.size_t range <>) of aliased interfaces.C.size_t;
   type bool_array               is array (interfaces.C.size_t range <>) of aliased swig.bool;

   type signed_char_array        is array (interfaces.C.size_t range <>) of aliased interfaces.C.signed_char;
   type unsigned_char_array      is array (interfaces.C.size_t range <>) of aliased interfaces.C.unsigned_char;

   type short_array              is array (interfaces.C.size_t range <>) of aliased interfaces.C.short;
   type int_array                is array (interfaces.C.size_t range <>) of aliased interfaces.C.int;
   type long_array               is array (interfaces.C.size_t range <>) of aliased interfaces.C.long;
   type long_long_array          is array (interfaces.C.size_t range <>) of aliased swig.long_Long;

   type unsigned_short_array     is array (interfaces.C.size_t range <>) of aliased interfaces.C.unsigned_short;
   type unsigned_array           is array (interfaces.C.size_t range <>) of aliased interfaces.C.unsigned;
   type unsigned_long_array      is array (interfaces.C.size_t range <>) of aliased interfaces.C.unsigned_long;
   type unsigned_long_long_array is array (interfaces.C.size_t range <>) of aliased swig.unsigned_long_Long;


   type int8_t_array             is array (interfaces.C.size_t range <>) of aliased swig.int8_t;
   type int16_t_array            is array (interfaces.C.size_t range <>) of aliased swig.int16_t;
   type int32_t_array            is array (interfaces.C.size_t range <>) of aliased swig.int32_t;
   type int64_t_array            is array (interfaces.C.size_t range <>) of aliased swig.int64_t;

   type uint8_t_array            is array (interfaces.C.size_t range <>) of aliased swig.uint8_t;
   type uint16_t_array           is array (interfaces.C.size_t range <>) of aliased swig.uint16_t;
   type uint32_t_array           is array (interfaces.C.size_t range <>) of aliased swig.uint32_t;
   type uint64_t_array           is array (interfaces.C.size_t range <>) of aliased swig.uint64_t;


   type float_array              is array (interfaces.C.size_t range <>) of aliased interfaces.C.c_Float;
   type double_array             is array (interfaces.C.size_t range <>) of aliased interfaces.C.double;
   type long_double_array        is array (interfaces.C.size_t range <>) of aliased interfaces.C.long_double;


end Swig;
