name        = "lace_gel_animation_demo"
description = "A demo of GEL's human animation."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"

executables   = ["launch_human_rig_demo"]
project-files = ["human_rig_demo.gpr"]

[[depends-on]]
lace_gel = "~0.1"
