-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;


package c_math_c
is

   --- Real
   --

   subtype Real is interfaces.C.C_float;

   type Real_array is array (interfaces.C.size_t range <>) of aliased c_math_c.Real;


   --- Index
   --

   subtype Index is interfaces.C.int;

   type Index_array is array (interfaces.C.size_t range <>) of aliased c_math_c.Index;


end c_math_c;
