-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;


package c_math_c.Vector_3
is

   --- Item
   --

   type Item is
      record
         x : aliased c_math_c.Real;
         y : aliased c_math_c.Real;
         z : aliased c_math_c.Real;
      end record;


   --- Items
   --

   type Items is array (interfaces.C.size_t range <>) of aliased c_math_c.Vector_3.Item;


   --- Pointer
   --

   type Pointer is access all c_math_c.Vector_3.Item;


   --- Pointers
   --

   type Pointers is array (interfaces.C.size_t range <>) of aliased c_math_c.Vector_3.Pointer;


   --- Pointer_pointer
   --

   type Pointer_pointer is access all c_math_c.Vector_3.Pointer;

   function construct return c_math_c.Vector_3.Item;

   function construct (x : in c_math_c.Real;
                       y : in c_math_c.Real;
                       z : in c_math_c.Real) return c_math_c.Vector_3.Item;



private

   function construct_v1 return c_math_c.Vector_3.Item;

   function construct return c_math_c.Vector_3.Item renames construct_v1;

   pragma import (C, construct_v1, "Ada_new_Vector_3__SWIG_0");

   function construct_v2 (x : in c_math_c.Real;
                          y : in c_math_c.Real;
                          z : in c_math_c.Real) return c_math_c.Vector_3.Item;

   function construct (x : in c_math_c.Real;
                       y : in c_math_c.Real;
                       z : in c_math_c.Real) return c_math_c.Vector_3.Item
     renames construct_v2;

   pragma import (C, construct_v2, "Ada_new_Vector_3__SWIG_1");


end c_math_c.Vector_3;
