-- This file is generated by SWIG. Please do *not* modify by hand.
--
with c_math_c.Pointers;


package c_math_c.pointer_Pointers
is

   --- Real_pointer_pointer
   --

   type Real_pointer_pointer is access all c_math_c.Pointers.Real_pointer;


   --- Index_pointer_pointer
   --

   type Index_pointer_pointer is access all c_math_c.Pointers.Index_pointer;


end c_math_c.pointer_Pointers;
