#!/bin/bash


echo
echo Removing prior build.
echo

rm *.ads
rm *.cxx


set -e


echo
echo Generating the binding.
echo

swig4ada  -ada -c++  -cpperraswarn    box2d_c.i 


echo
echo Pretty printing.
echo

gnatpp  -rnb  -I/usr/local/include -I../../c_math/source/thin *.ads
indent  -sob  -di16  *.cxx

