name        = "lace_opengl"
description = "Provides an openGL engine."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"
tags     = ["graphics", "3d"]

project-files = ["library/opengl.gpr"]

[[depends-on]]
lace_collada = "~0.1"
libfreetype = "^2"

[depends-on."case(os)"."windows"]
libmesa = "*"

[environment.'case(distribution)'.msys2.C_INCLUDE_PATH]
append = "${DISTRIB_ROOT}/mingw64/include/freetype2"
