#!/bin/bash

set -e

########
## Clean
#
rm -fr ./dsa
gprclean -r -P ../gel_demo.gpr -Xopengl_platform=egl -Xopengl_profile=lean


#########
## Build
#
po_gnatdist -Xrestrictions=xgc                                    \
            -Xopengl_platform=egl                                 \
            -Xopengl_profile=lean                                 \
            -P demo_dsa.gpr                                       \
            simple_dsa.cfg                                        \
            -cargs                                                \
            -I$LACE/3-mid/physics/implement/box2d/contrib/include \
            -g                                                    \
            -largs                                                \
            -g


cp bin/server_partition test/test_server
cp bin/client_partition test/test_client_1
cp bin/client_partition test/test_client_2
