-- This file is generated by SWIG. Please do not modify by hand.
--
with Interfaces.C;
with Interfaces.C.Pointers;
with System;

package box2d_c.Pointers is

   use System;


   -- Shape_Pointer
   --
   package C_Shape_Pointers is new interfaces.c.Pointers
     (Index         => interfaces.c.size_t, Element => box2d_c.Shape,
      element_Array => box2d_c.Shape_Array, default_Terminator => null_Address);

   subtype Shape_Pointer is C_Shape_Pointers.Pointer;

   -- Shape_Pointer_Array
   --
   type Shape_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased box2d_c.Pointers
       .Shape_Pointer;

   -- Object_Pointer
   --
   package C_Object_Pointers is new interfaces.c.Pointers
     (Index         => interfaces.c.size_t, Element => box2d_c.Object,
      element_Array => box2d_c.Object_Array, default_Terminator => null_Address);

   subtype Object_Pointer is C_Object_Pointers.Pointer;

   -- Object_Pointer_Array
   --
   type Object_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased box2d_c.Pointers
       .Object_Pointer;

   -- Joint_Pointer
   --
   package C_Joint_Pointers is new interfaces.c.Pointers
     (Index         => interfaces.c.size_t, Element => box2d_c.Joint,
      element_Array => box2d_c.Joint_Array, default_Terminator => null_Address);

   subtype Joint_Pointer is C_Joint_Pointers.Pointer;

   -- Joint_Pointer_Array
   --
   type Joint_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased box2d_c.Pointers
       .Joint_Pointer;

   -- Space_Pointer
   --
   package C_Space_Pointers is new interfaces.c.Pointers
     (Index         => interfaces.c.size_t, Element => box2d_c.Space,
      element_Array => box2d_c.Space_Array, default_Terminator => null_Address);

   subtype Space_Pointer is C_Space_Pointers.Pointer;

   -- Space_Pointer_Array
   --
   type Space_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased box2d_c.Pointers
       .Space_Pointer;

   -- b2Joint_Pointer
   --
   package C_b2Joint_Pointers is new interfaces.c.Pointers
     (Index         => interfaces.c.size_t, Element => box2d_c.b2Joint,
      element_Array => box2d_c.b2Joint_Array, default_Terminator => null_Address);

   subtype b2Joint_Pointer is C_b2Joint_Pointers.Pointer;

   -- b2Joint_Pointer_Array
   --
   type b2Joint_Pointer_Array is
     array
       (Interfaces.C.size_t range <>) of aliased box2d_c.Pointers
       .b2Joint_Pointer;

end box2d_c.Pointers;
