-- This file is generated by SWIG. Please do not modify by hand.
--
with
     interfaces.C,
     interfaces.C.Pointers;


package box2d_c.joint_Cursor
is

   --- Item
   --

   type Item is
      record
         Joint : access box2d_c.b2Joint;
      end record;

   --- Item_array
   --
   type Item_array is array (interfaces.C.size_t range <>) of aliased box2d_c.joint_Cursor.Item;

   --- Pointer
   --
   package C_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                    Element            => box2d_c.joint_Cursor.Item,
                                                    Element_array      => box2d_c.joint_Cursor.item_array,
                                                    default_Terminator => (Joint => null));

   subtype Pointer is C_Pointers.Pointer;

   --- Pointer_array
   --
   type Pointer_array is array (interfaces.C.size_t range <>) of aliased box2d_c.joint_Cursor.Pointer;

   --- Pointer_pointer
   --
   package C_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                            Element            => box2d_c.joint_Cursor.Pointer,
                                                            Element_array      => box2d_c.joint_Cursor.Pointer_array,
                                                            default_Terminator => null);

   subtype Pointer_pointer is C_Pointer_Pointers.Pointer;

   function construct return box2d_c.joint_Cursor.Item;

   procedure destruct_0 (Self : in box2d_c.joint_Cursor.Item);

   procedure destruct (Self : in box2d_c.joint_Cursor.Item);



private

   pragma import (CPP, construct,  "ada_new_joint_Cursor_joint_Cursor");
   pragma import (CPP, destruct_0, "_ZN12joint_CursorD1Ev");
   pragma import (CPP, destruct,   "_ZN12joint_CursorD1Ev");


end box2d_c.joint_Cursor;
