-- This file is generated by SWIG. Please do not modify by hand.
--
with
     c_math_c.Vector_3,
     interfaces.C,
     interfaces.C.Pointers;


package box2d_c.b2d_Contact
is

   --- Item
   --

   type Item is
      record
         Object_A : access  box2d_c.Object;
         Object_B : access  box2d_c.Object;
         Site     : aliased c_math_c.Vector_3.Item;
      end record;

   --- Item_array
   --
   type Item_array is array (interfaces.C.size_t range <>) of aliased box2d_c.b2d_Contact.Item;

   --- Pointer
   --
   package C_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                    Element            => box2d_c.b2d_Contact.Item,
                                                    Element_array      => box2d_c.b2d_Contact.item_array,
                                                    default_Terminator => (Object_A | Object_B => null,
                                                                           Site                => (x | y | z => 0.0)));

   subtype Pointer is C_Pointers.Pointer;

   --- Pointer_array
   --
   type Pointer_array is array (interfaces.C.size_t range <>) of aliased box2d_c.b2d_Contact.Pointer;

   --- Pointer_pointer
   --
   package C_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                            Element            => box2d_c.b2d_Contact.Pointer,
                                                            Element_array      => box2d_c.b2d_Contact.Pointer_array,
                                                            default_Terminator => null);

   subtype Pointer_pointer is C_Pointer_Pointers.Pointer;

   function construct return box2d_c.b2d_Contact.Item;

   procedure destruct_0 (Self : in box2d_c.b2d_Contact.Item);

   procedure destruct (Self : in box2d_c.b2d_Contact.Item);



private

   pragma import (CPP, construct,  "ada_new_b2d_Contact_b2d_Contact");
   pragma import (CPP, destruct_0, "_ZN11b2d_ContactD1Ev");
   pragma import (CPP, destruct,   "_ZN11b2d_ContactD1Ev");


end box2d_c.b2d_Contact;
