-- This file is generated by SWIG. Please do not modify by hand.
--
with
     box2d_c.Pointers,

     interfaces.C,
     interfaces.C.Pointers;

use interfaces.C;


package box2d_c.pointer_Pointers
is

   --- Shape_pointer_pointer
   --

   package C_Shape_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                                  Element            => box2d_c.Pointers.Shape_pointer,
                                                                  Element_array      => box2d_c.Pointers.Shape_pointers,
                                                                  default_Terminator => null);

   subtype Shape_pointer_pointer is C_Shape_Pointer_Pointers.Pointer;


   --- Object_pointer_pointer
   --

   package C_Object_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                                   Element            => box2d_c.Pointers.Object_pointer,
                                                                   Element_array      => box2d_c.Pointers.Object_pointers,
                                                                   default_Terminator => null);

   subtype Object_pointer_pointer is C_Object_Pointer_Pointers.Pointer;


   --- Joint_pointer_pointer
   --

   package C_Joint_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                                  Element            => box2d_c.Pointers.Joint_pointer,
                                                                  Element_array      => box2d_c.Pointers.Joint_pointers,
                                                                  default_Terminator => null);

   subtype Joint_pointer_pointer is C_Joint_Pointer_Pointers.Pointer;


   --- Space_pointer_pointer
   --

   package C_Space_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                                  Element            => box2d_c.Pointers.Space_pointer,
                                                                  Element_array      => box2d_c.Pointers.Space_pointers,
                                                                  default_Terminator => null);

   subtype Space_pointer_pointer is C_Space_Pointer_Pointers.Pointer;


   --- b2Joint_pointer_pointer
   --

   package C_b2Joint_Pointer_Pointers is new interfaces.C.Pointers (Index              => interfaces.C.size_t,
                                                                    Element            => box2d_c.Pointers.b2Joint_pointer,
                                                                    Element_array      => box2d_c.Pointers.b2Joint_pointers,
                                                                    default_Terminator => null);

   subtype b2Joint_pointer_pointer is C_b2Joint_Pointer_Pointers.Pointer;


end box2d_c.pointer_Pointers;
