-- This file is generated by SWIG. Please do not modify by hand.
--
with
     interfaces.C,
     interfaces.C.Pointers,
     System;


package box2d_c.Pointers
is
   use System;


   --- Shape_pointer
   --

   package C_Shape_Pointers is new interfaces.c.Pointers (Index              => interfaces.c.size_t,
                                                          Element            => box2d_c.Shape,
                                                          Element_array      => box2d_c.Shape_array,
                                                          default_Terminator => null_Address);

   subtype Shape_pointer is C_Shape_Pointers.Pointer;


   --- Shape_pointers
   --

   type Shape_pointers is array (interfaces.C.size_t range <>) of aliased box2d_c.Pointers.Shape_pointer;


   --- Object_pointer
   --

   package C_Object_Pointers is new interfaces.c.Pointers (Index              => interfaces.c.size_t,
                                                           Element            => box2d_c.Object,
                                                           Element_array      => box2d_c.Object_array,
                                                           default_Terminator => null_Address);

   subtype Object_pointer is C_Object_Pointers.Pointer;


   --- Object_pointers
   --

   type Object_pointers is array (interfaces.C.size_t range <>) of aliased box2d_c.Pointers.Object_pointer;


   --- Joint_pointer
   --

   package C_Joint_Pointers is new interfaces.c.Pointers (Index              => interfaces.c.size_t,
                                                          Element            => box2d_c.Joint,
                                                          Element_array      => box2d_c.Joint_array,
                                                          default_Terminator => null_Address);

   subtype Joint_pointer is C_Joint_Pointers.Pointer;


   --- Joint_pointers
   --

   type Joint_pointers is array (interfaces.C.size_t range <>) of aliased box2d_c.Pointers.Joint_pointer;


   --- Space_pointer
   --

   package C_Space_Pointers is new interfaces.c.Pointers (Index              => interfaces.c.size_t,
                                                          Element            => box2d_c.Space,
                                                          Element_array      => box2d_c.Space_array,
                                                          default_Terminator => null_Address);

   subtype Space_pointer is C_Space_Pointers.Pointer;


   --- Space_pointers
   --

   type Space_pointers is array (interfaces.C.size_t range <>) of aliased box2d_c.Pointers.Space_pointer;


   --- b2Joint_pointer
   --

   package C_b2Joint_Pointers is new interfaces.c.Pointers (Index              => interfaces.c.size_t,
                                                            Element            => box2d_c.b2Joint,
                                                            Element_array      => box2d_c.b2Joint_array,
                                                            default_Terminator => null_Address);

   subtype b2Joint_pointer is C_b2Joint_Pointers.Pointer;


   --- b2Joint_pointers
   --

   type b2Joint_pointers is array (interfaces.C.size_t range <>) of aliased box2d_c.Pointers.b2Joint_pointer;


end box2d_c.Pointers;
