name        = "lace_collada"
description = "A Collada parser."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"
tags     = ["model", "3d"]

project-files = ["library/collada.gpr"]

[[depends-on]]
lace_math = "~0.1"
lace_xml  = "~0.1"
