-- This file is generated by SWIG. Please do *not* modify by hand.
--
with
     osmesa_c.Pointers,

     interfaces.C,
     interfaces.C.Strings,

     Swig,
     swig.Pointers;


package osmesa_c.Binding
is

   function OSMesaCreateContext (format    : in osmesa_c.GLenum;
                                 sharelist : in osmesa_c.OSMesaContext) return osmesa_c.OSMesaContext;

   function OSMesaCreateContextExt (format      : in osmesa_c.GLenum;
                                    depthBits   : in osmesa_c.GLint;
                                    stencilBits : in osmesa_c.GLint;
                                    accumBits   : in osmesa_c.GLint;
                                    sharelist   : in osmesa_c.OSMesaContext) return osmesa_c.OSMesaContext;

   procedure OSMesaDestroyContext (ctx : in osmesa_c.OSMesaContext);

   function OSMesaMakeCurrent (ctx      : in osmesa_c.OSMesaContext;
                               buffer   : in Swig.void_ptr;
                               the_type : in osmesa_c.GLenum;
                               width    : in osmesa_c.GLsizei;
                               height   : in osmesa_c.GLsizei) return osmesa_c.GLboolean;

   function OSMesaGetCurrentContext return osmesa_c.OSMesaContext;

   procedure OSMesaPixelStore (pname : in osmesa_c.GLint;
                               value : in osmesa_c.GLint);

   procedure OSMesaGetIntegerv (pname : in osmesa_c.GLint;
                                value : in osmesa_c.Pointers.GLint_Pointer);

   function OSMesaGetDepthBuffer (c             : in osmesa_c.OSMesaContext;
                                  width         : in osmesa_c.Pointers.GLint_Pointer;
                                  height        : in osmesa_c.Pointers.GLint_Pointer;
                                  bytesPerValue : in osmesa_c.Pointers.GLint_Pointer;
                                  buffer        : in Swig.Pointers.void_ptr_Pointer) return osmesa_c.GLboolean;

   function OSMesaGetColorBuffer (c      : in osmesa_c.OSMesaContext;
                                  width  : in osmesa_c.Pointers.GLint_Pointer;
                                  height : in osmesa_c.Pointers.GLint_Pointer;
                                  format : in osmesa_c.Pointers.GLint_Pointer;
                                  buffer : in Swig.Pointers.void_ptr_Pointer) return osmesa_c.GLboolean;

   function OSMesaGetProcAddress (funcName : in interfaces.C.Strings.chars_ptr) return osmesa_c.OSMESAproc;

   procedure OSMesaColorClamp (enable : in osmesa_c.GLboolean);

   procedure OSMesaPostprocess (osmesa       : in osmesa_c.OSMesaContext;
                                filter       : in interfaces.C.Strings.chars_ptr;
                                enable_value : in interfaces.C.unsigned);



private

   pragma import (C, OSMesaCreateContext,     "Ada_OSMesaCreateContext");
   pragma import (C, OSMesaCreateContextExt,  "Ada_OSMesaCreateContextExt");
   pragma import (C, OSMesaDestroyContext,    "Ada_OSMesaDestroyContext");
   pragma import (C, OSMesaMakeCurrent,       "Ada_OSMesaMakeCurrent");
   pragma import (C, OSMesaGetCurrentContext, "Ada_OSMesaGetCurrentContext");
   pragma import (C, OSMesaPixelStore,        "Ada_OSMesaPixelStore");
   pragma import (C, OSMesaGetIntegerv,       "Ada_OSMesaGetIntegerv");
   pragma import (C, OSMesaGetDepthBuffer,    "Ada_OSMesaGetDepthBuffer");
   pragma import (C, OSMesaGetColorBuffer,    "Ada_OSMesaGetColorBuffer");
   pragma import (C, OSMesaGetProcAddress,    "Ada_OSMesaGetProcAddress");
   pragma import (C, OSMesaColorClamp,        "Ada_OSMesaColorClamp");
   pragma import (C, OSMesaPostprocess,       "Ada_OSMesaPostprocess");


end osmesa_c.Binding;
