name        = "lace_gel"
description = "A 2D/3D game engine library (GEL)."
version     = "1.0.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace"

project-files = ["library/gel.gpr"]

[[depends-on]]
lace_opengl  = "^1.0.0"
lace_physics = "^1.0.0"
sdlada       = "2.5.4-1"
