name        = "lace_gel"
description = "A 2D/3D game engine library (GEL)."
version     = "0.1.1"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace-alire"

project-files = ["library/gel.gpr"]

[[depends-on]]
lace_opengl  = "~0.1"
lace_physics = "~0.1"
sdlada       = "2.5.4-1"
