package gl.Binding
--
-- Provides functions common to all openGL profiles.
--
is

   procedure glActiveTexture     (Texture  : in     GLenum);
   procedure glBindTexture       (Target   : in     GLenum;
                                  Texture  : in     GLuint);
   procedure glBlendFunc         (sFactor  : in     GLenum;
                                  dFactor  : in     GLenum);
   procedure glClear             (Mask     : in     GLbitfield);
   procedure glClearColor        (Red      : in     GLclampf;
                                  Green    : in     GLclampf;
                                  Blue     : in     GLclampf;
                                  Alpha    : in     GLclampf);
   procedure glClearDepthf       (Depth    : in     GLclampf);
   procedure glClearStencil      (S        : in     GLint);
   procedure glColorMask         (Red      : in     GLboolean;
                                  Green    : in     GLboolean;
                                  Blue     : in     GLboolean;
                                  Alpha    : in     GLboolean);
   procedure glCullFace          (Mode     : in     GLenum);
   procedure glDepthFunc         (Func     : in     GLenum);
   procedure glDepthMask         (Flag     : in     GLboolean);
   procedure glDepthRangef       (zNear    : in     GLclampf;
                                  zFar     : in     GLclampf);
   procedure glDisable           (Cap      : in     GLenum);
   procedure glDrawArrays        (Mode     : in     GLenum;
                                  First    : in     GLint;
                                  Count    : in     GLsizei);
   procedure glDrawElements      (Mode     : in     GLenum;
                                  Count    : in     GLsizei;
                                  the_Type : in     GLenum;
                                  Indices  : access GLvoid);
   procedure glEnable            (Cap      : in     GLenum);
   procedure glFinish;
   procedure glFlush;
   procedure glFrontFace         (Mode     : in     GLenum);
   procedure glGenTextures       (N        : in     GLsizei;
                                  Textures : access GLuint);
   function  glGetError                  return GLenum;
   procedure glGetBooleanv       (pName    : in     GLenum;
                                  Params   : access GLboolean);
   procedure glGetFloatv         (pName    : in     GLenum;
                                  Params   : access GLfloat);
   procedure glGetIntegerv       (pName    : in     GLenum;
                                  Params   : access GLint);
   function  glGetString         (Name     : in     GLenum)  return access GLubyte;
   procedure glGetTexParameteriv (Target   : in     GLenum;
                                  pName    : in     GLenum;
                                  Params   : access GLint);
   procedure glHint              (Target   : in     GLenum;
                                  Mode     : in     GLenum);
   function  glIsEnabled         (Cap      : in     GLenum)   return GLboolean;
   procedure glLineWidth         (Width    : in     GLfloat);
   procedure glPixelStorei       (pName    : in     GLenum;
                                  Param    : in     GLint);
   procedure glPolygonOffset     (Factor   : in     GLfloat;
                                  Units    : in     GLfloat);
   procedure glReadPixels        (X        : in     GLint;
                                  Y        : in     GLint;
                                  Width    : in     GLsizei;
                                  Height   : in     GLsizei;
                                  Format   : in     GLenum;
                                  the_Type : in     GLenum;
                                  Pixels   : access GLvoid);
   procedure glScissor           (X        : in     GLint;
                                  Y        : in     GLint;
                                  Width    : in     GLsizei;
                                  Height   : in     GLsizei);
   procedure glStencilFunc       (Func     : in     GLenum;
                                  Ref      : in     GLint;
                                  Mask     : in     GLuint);
   procedure glStencilMask       (Mask     : in     GLuint);
   procedure glStencilOp         (Fail     : in     GLenum;
                                  zFail    : in     GLenum;
                                  zPass    : in     GLenum);
   procedure glTexImage2D        (Target   : in     GLenum;
                                  Level    : in     GLint;
                                  internalFormat
                                  : in     GLenum;
                                  Width    : in     GLsizei;
                                  Height   : in     GLsizei;
                                  Border   : in     GLint;
                                  Format   : in     GLenum;
                                  the_Type : in     GLenum;
                                  Pixels   : access GLvoid);
   procedure glTexSubImage2D     (Target   : in     GLenum;
                                  Level    : in     GLint;
                                  xOffset  : in     GLint;
                                  yOffset  : in     GLint;
                                  Width    : in     GLsizei;
                                  Height   : in     GLsizei;
                                  Format   : in     GLenum;
                                  the_Type : in     GLenum;
                                  Pixels   : access GLvoid);
   procedure glTexParameteri     (Target   : in     GLenum;
                                  pName    : in     GLenum;
                                  Param    : in     GLint);
   procedure glViewport          (X        : in     GLint;
                                  Y        : in     GLint;
                                  Width    : in     GLsizei;
                                  Height   : in     GLsizei);



private

   pragma import (StdCall, glActiveTexture,     "glActiveTexture");
   pragma import (Stdcall, glBindTexture,       "glBindTexture");
   pragma import (Stdcall, glBlendFunc,         "glBlendFunc");
   pragma import (Stdcall, glClear,             "glClear");
   pragma import (Stdcall, glClearColor,        "glClearColor");
   pragma import (Stdcall, glClearDepthf,       "glClearDepthf");
   pragma import (Stdcall, glClearStencil,      "glClearStencil");
   pragma import (Stdcall, glColorMask,         "glColorMask");
   pragma import (Stdcall, glCullFace,          "glCullFace");
   pragma import (Stdcall, glDepthFunc,         "glDepthFunc");
   pragma import (Stdcall, glDepthMask,         "glDepthMask");
   pragma import (Stdcall, glDepthRangef,       "glDepthRangef");
   pragma import (Stdcall, glDisable,           "glDisable");
   pragma import (Stdcall, glDrawArrays,        "glDrawArrays");
   pragma import (Stdcall, glDrawElements,      "glDrawElements");
   pragma import (Stdcall, glEnable,            "glEnable");
   pragma import (Stdcall, glFinish,            "glFinish");
   pragma import (Stdcall, glFlush,             "glFlush");
   pragma import (Stdcall, glFrontFace,         "glFrontFace");
   pragma import (Stdcall, glGenTextures,       "glGenTextures");
   pragma import (Stdcall, glGetError,          "glGetError");
   pragma import (StdCall, glGetBooleanv,       "glGetBooleanv");
   pragma import (StdCall, glGetFloatv,         "glGetFloatv");
   pragma import (StdCall, glGetIntegerv,       "glGetIntegerv");
   pragma import (StdCall, glGetString,         "glGetString");
   pragma import (StdCall, glGetTexParameteriv, "glGetTexParameteriv");
   pragma import (Stdcall, glHint,              "glHint");
   pragma import (Stdcall, glIsEnabled,         "glIsEnabled");
   pragma import (Stdcall, glLineWidth,         "glLineWidth");
   pragma import (Stdcall, glPixelStorei,       "glPixelStorei");
   pragma import (Stdcall, glPolygonOffset,     "glPolygonOffset");
   pragma import (StdCall, glReadPixels,        "glReadPixels");
   pragma import (Stdcall, glScissor,           "glScissor");
   pragma import (Stdcall, glStencilFunc,       "glStencilFunc");
   pragma import (Stdcall, glStencilMask,       "glStencilMask");
   pragma import (Stdcall, glStencilOp,         "glStencilOp");
   pragma import (StdCall, glTexImage2D,        "glTexImage2D");
   pragma import (StdCall, glTexSubImage2D,     "glTexSubImage2D");
   pragma import (Stdcall, glTexParameteri,     "glTexParameteri");
   pragma import (Stdcall, glViewport,          "glViewport");


end gl.Binding;
